server:
  port: 8888

spring:
  application:
    name: ducker-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Ducker-Inc/ducker-configs

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
